pip install jsonlib
pip install requests
pip install os-sys
pip install times
pip install threaded
pip install random2
pip install strings
pip install pybase64
pip install syspath
pip install asyncio
pip install more-itertools
pip install colorama
pip install pypresence
pip install discord-ext-bot
pip install discord.py
pip install aiohttp==2.2.5
pip install discord-webhook
pip install webhooks
pip install jsonlib
pip install regex
pip install pyPrivnote
pip install DateTime
pip install urllib3
pip install subprocess.run
pip install win10toast
pip install ctypes-callable
pip install ctypes-windows-sdk
